name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  BASE_IMAGE_STABILITY_TAG: 2.10.6
  MEMCACHED16: '1.6.15'

jobs:
  memcached-16:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.MEMCACHED16 }}
        tags: ${{ env.MEMCACHED16 }}-alpine3.15,1.6-alpine3.15,1-alpine3.15,${{ env.MEMCACHED16 }},1.6,1,alpine3.15,latest
        workdir: .
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.15
  memcached-16-alpine313:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.MEMCACHED16 }}
        tags: ${{ env.MEMCACHED16 }}-alpine3.13,1-alpine3.13,alpine3.13
        workdir: .
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.15
